bank/bank/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from bank import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('bankapp.urls')),
    path('formsapp/',include('formsapp.urls')),
]
if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

bank/bankapp/urls.py
from . import views
from django.urls import path

urlpatterns =[
    path('',views.demo,name='demo'),

]

bank/formsapp/urls.py
from . import views
from django.urls import path

urlpatterns=[
    path('register',views.register,name='register'),
    path('login',views.login,name='login'),
    path('details',views.details,name='details'),
    path('add',views.add,name='add'),
    path('logout',views.logout,name='logout'),
    path('accepted',views.accepted,name='accepted'),
    path('user_form',views.user_form,name='user_form'),
    path('ajax/load-branches', views.load_branches, name='load_branches'),

]

bank/bankapp/models.py
from django.db import models

# Create your models here.

bank/formsapp/models.py
from django.db import models

# Create your models here.
class District(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Branch(models.Model):
    name = models.CharField(max_length=50)
    district = models.ForeignKey(District, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class AccountType(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

bank/formsapp/forms.py
from django import forms
from .models import District, Branch, AccountType

class UserForm(forms.Form):
    name = forms.CharField(max_length=100)
    date_of_birth = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    gender = forms.ChoiceField(choices=(('M', 'Male'), ('F', 'Female'), ('O', 'Other')))
    phone_number = forms.CharField(max_length=20)
    email = forms.EmailField()
    address = forms.CharField(widget=forms.Textarea)
    district = forms.ModelChoiceField(queryset=District.objects.all(), empty_label="Select district", widget=forms.Select(attrs={'onChange': 'load_branches();'}))
    branch = forms.ModelChoiceField(queryset=Branch.objects.none(), empty_label="Select branch", widget=forms.Select())
    account_type = forms.ModelChoiceField(queryset=AccountType.objects.all())
    materials = forms.MultipleChoiceField(choices=(('Cheque book', 'Cheque book'), ('ATM card', 'ATM card'), ('Passbook', 'Passbook')), widget=forms.CheckboxSelectMultiple)

bank/bankapp/views.py
from django.shortcuts import render

# Create your views here.

def demo(request):
    return render(request,"index.html")

bank/formsapp/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.contrib import messages,auth
from . forms import UserForm
from .models import Branch

# Create your views here.
def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        confirmpassword = request.POST['confirm_password']
        if password == confirmpassword:
            if User.objects.filter(username=username).exists():
                messages.info(request, "Username exists")
                return redirect('register')
            user = User.objects.create_user(username=username, password=password)
            user.save();
            return redirect('login')
        else:
            messages.info(request, "password not matching")
    return render(request,"register.html")

def login(request):
    if request.method=='POST':
        username= request.POST['username']
        password = request.POST['password']
        user=auth.authenticate(username=username,password=password)

        if user is not None:
            auth.login(request,user)
            return redirect('details')
        else:
            messages.info(request,"invalid credintials")
            return redirect('login')

    return render(request,"login.html")

def details(request):

    return render(request,"details.html")

def add(request):
    if request.method == 'POST':

        return redirect('accepted')
    return render(request,"add.html")

def logout(request):

    return redirect ('/')

def accepted(request):
    return render(request,"accepted.html")

def user_form(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        return redirect('accepted')
        pass
    else:
        form = UserForm()
    return render(request, 'user_form.html', {'form': form})

def load_branches(request):
    district_id = request.GET.get('district')
    branches = Branch.objects.filter(district_id=district_id).order_by('name')
    return render(request, 'branch_dropdown_list_options.html', {'branches': branches})

bank/templates/accepted.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Finish</title>
</head>
<body>
<h1>Welcome to Unity Banks</h1>

<h3>Your details has been accepted.<br>
    <br>
You will receive the account number via SMS within 24 Hrs.</h3>

<h4>Happy banking</h4>

    Please Click <a href='/'>Here</a>  for returning to home page.


</body>
</html>

bank/templates/add.html
from django import forms
from .models import District, Branch
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Form</title>
</head>
<body>
<form method="post" action="add">
    {% csrf_token %}
    <input type="text" name="name" placeholder="Name"><br>
    <input type="date" name="date_of_birth" placeholder="Date Of Birth"><br>
    <input type="number" name="age" placeholder="Age"><br>
    <input type="radio" name="gender" placeholder="Gender">Male<input type="radio" name="gender" placeholder="Gender">Female<br>
    <input type="number" name="phone_number" placeholder="Phone Number"><br>
    <input type="email" name="email" placeholder="Email ID"><br>
    <input type="text" name="address" placeholder="Address"><br>
    <input type=""
    <input type="checkbox">Debit card<input type="checkbox">Credit Card<input type="checkbox">Cheque Book<br>
    <input type="submit" >
    <a class="btn btn-secondary" href='logout'>Logout</a>
</form>
</body>
</html>

bank/templates/branch_dropdown_list_options.html
{% for branch in branches %}
<option value="{{ branch.pk }}">{{ branch.name }}</option>
{% endfor %}

bank/templates/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Details</title>
</head>
<body>
<form method="POST" action="details">
    {% csrf_token %}
<p> Please click the below button to submit your details and start the relationship with us</p>
    <div>
            <a class="btn btn-secondary" href='user_form'>Add</a>
</div>

</form>
</body>
</html>

bank/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<h2>Login</h2>
<body>
<form action="login" method="POST">
    {% csrf_token %}
    <input type="text" name="username" placeholder="User Name"><br>
    <input type="password" name="password" placeholder="Password"><br>
    <input type="submit" ><br>
    <br>
    <br>
    <br>

    Please Click <a href="register">Here</a> to register if your are new.
</form>

</body>
</html>

bank/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
</head>
<body>
<h2>Register Here</h2>
<form action="register" method="POST">
    {% csrf_token %}
    <input type="text" name="username" placeholder="User Name"><br>
    <input type="password" name="password" placeholder="Password"><br>
    <input type="password" name="confirm_password" placeholder="Confirm Password"><br>
    <input type="submit" ><br>
</form>


</body>
</html>

bank/templates/user_form.html
{% block content %}

  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button><br>
    <div>
    <a class="btn btn-secondary" href='logout'>Logout</a>
      </div>
  </form>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script>
    function load_branches() {
      var district_id = $('#id_district').val();
      $.ajax({
        url: 'ajax/load-branches',
        data: {
          'district': district_id
        },
        success: function (data) {
          $('#id_branch').html(data);
        }
      });
    }
  </script>
{% endblock %}